### ISSUE TITLE
Handling Orphaned Child Comments When Parent is Deleted

### ISSUE THREAD

**Issue by Pharmakron** [Blue-Davinci/Aggregate-FronteEnd#1]
Currently, in the comment system, when a parent comment is deleted, all its child comments are also removed from the display, even though am sure they still exist. This behavior leads to the loss of potentially valuable discussions that are nested under the deleted parent comment. The expected behavior is for child comments to remain visible and be promoted to top-level comments if their parent comment is deleted.

**Steps to Reproduce**
Post a parent comment.
Reply to the parent comment with one or more child comments.
Delete the parent comment.

**Expected Behavior**
After deleting the parent comment, all child comments should be promoted to top-level comments, maintaining their visibility in the discussion thread.

**Actual Behavior**
Once the parent comment is deleted, all child comments also disappear from the thread, even though they are not actually deleted from the database.

**Possible Solution**
Adjust the comment organization logic to check if a child comment's parent is missing from the map and, if so, treat it as a top-level comment.

**Comment by Blue-Davinci** [comment]
Thank you for the issue.
Quite fortuitous that am working on a fix for that atm.
Should be pushing an update in a couple of minutes.

**Comment by Blue-Davinci** [comment]
> Currently, in the comment system, when a parent comment is deleted, all its child comments are also removed from the display, even though am sure they still exist. This behavior leads to the loss of potentially valuable discussions that are nested under the deleted parent comment. The expected behavior is for child comments to remain visible and be promoted to top-level comments if their parent comment is deleted.
> 
> **Steps to Reproduce** Post a parent comment. Reply to the parent comment with one or more child comments. Delete the parent comment.
> 
> **Expected Behavior** After deleting the parent comment, all child comments should be promoted to top-level comments, maintaining their visibility in the discussion thread.
> 
> **Actual Behavior** Once the parent comment is deleted, all child comments also disappear from the thread, even though they are not actually deleted from the database.
> 
> **Possible Solution** Adjust the comment organization logic to check if a child comment's parent is missing from the map and, if so, treat it as a top-level comment.

Done, the issue plus a few others i identified have been successfully resolved. Here is a summary of the fix:
- Modified comment organization logic by including checks to see if a child comment parent was missing, if so the child comments are treated as the top level comments
- Changes are reflected immediately on the client side by updating the comments and reorganizing them
- Fixed the issue where multiple event dispatches were fired when a parent comment/ child comment in a thread was deleted causing a cascade of delete requests.
- Fixed an issue where a user still had edit and delete capability on a deleted comment. Completely removed  placeholders for deleted comments and just upgraded a child to the parent.

Thanks for bringing the issue mate :)

**Comment by Pharmakron** [comment]
> > Currently, in the comment system, when a parent comment is deleted, all its child comments are also removed from the display, even though am sure they still exist. This behavior leads to the loss of potentially valuable discussions that are nested under the deleted parent comment. The expected behavior is for child comments to remain visible and be promoted to top-level comments if their parent comment is deleted.
> > **Steps to Reproduce** Post a parent comment. Reply to the parent comment with one or more child comments. Delete the parent comment.
> > **Expected Behavior** After deleting the parent comment, all child comments should be promoted to top-level comments, maintaining their visibility in the discussion thread.
> > **Actual Behavior** Once the parent comment is deleted, all child comments also disappear from the thread, even though they are not actually deleted from the database.
> > **Possible Solution** Adjust the comment organization logic to check if a child comment's parent is missing from the map and, if so, treat it as a top-level comment.
> 
> Done, the issue plus a few others i identified have been successfully resolved. Here is a summary of the fix:
> 
> * Modified comment organization logic by including checks to see if a child comment parent was missing, if so the child comments are treated as the top level comments
> * Changes are reflected immediately on the client side by updating the comments and reorganizing them
> * Fixed the issue where multiple event dispatches were fired when a parent comment/ child comment in a thread was deleted causing a cascade of delete requests.
> * Fixed an issue where a user still had edit and delete capability on a deleted comment. Completely removed  placeholders for deleted comments and just upgraded a child to the parent.
> 
> Thanks for bringing the issue mate :)

Muy bien!!!
Looks okay and thank you as well!

**Comment by Blue-Davinci** [comment]
Issue Closed.
